# generated by datamodel-codegen:
#   filename:  schema.json

from __future__ import annotations

from datetime import date, datetime
from enum import Enum
from typing import Any, Optional
from uuid import UUID

from pydantic import BaseModel, Field, conint


class Model(BaseModel):
    __root__: Any


class AccessLevel(Enum):
    publico = 'publico'
    interno = 'interno'
    confidencial = 'confidencial'


class AuditAction(Enum):
    crear = 'crear'
    modificar = 'modificar'
    eliminar = 'eliminar'
    consultar = 'consultar'
    descargar = 'descargar'
    restaurar_version = 'restaurar_version'
    cambiar_permisos = 'cambiar_permisos'
    aprobar = 'aprobar'
    rechazar = 'rechazar'


class DocumentStatus(Enum):
    borrador = 'borrador'
    vigente = 'vigente'
    archivado = 'archivado'
    eliminado = 'eliminado'


class DocumentType(Enum):
    informe = 'informe'
    resolucion = 'resolucion'
    contrato = 'contrato'
    correspondencia = 'correspondencia'
    proyecto = 'proyecto'
    otro = 'otro'


class DocumentVersion(BaseModel):
    autor: str = Field(..., description='Usuario o sistema que realizó la modificación')
    comentario: Optional[str] = Field(
        None, description='Comentario o descripción del cambio'
    )
    documento_id: UUID = Field(
        ..., description='ID del documento al que pertenece esta versión'
    )
    fecha: datetime = Field(..., description='Fecha de creación de la versión')
    hash_anterior: Optional[str] = Field(
        None,
        description='Referencia opcional al hash de la versión anterior (para trazabilidad encadenada)',
    )
    hash_contenido: str = Field(..., description='Hash de integridad de esta versión')
    id: UUID = Field(..., description='Identificador único de la versión')
    numero: str = Field(..., description='Número o etiqueta de versión (v1, v2, etc.)')


class FileFormat(Enum):
    pdf = 'pdf'
    docx = 'docx'
    xlsx = 'xlsx'
    txt = 'txt'
    csv = 'csv'
    xml = 'xml'
    json = 'json'
    png = 'png'
    jpg = 'jpg'
    otro = 'otro'


class RetentionRule(BaseModel):
    disposicion_final: str = Field(
        ..., description='Disposición final (eliminación, conservación, transferencia)'
    )
    fecha_creacion: date = Field(
        ..., description='Fecha de creación o aprobación de la regla'
    )
    id: UUID = Field(..., description='Identificador único de la regla TRD')
    observaciones: Optional[str] = Field(
        None, description='Observaciones o referencias normativas'
    )
    plazo_central: conint(ge=0, le=65535) = Field(
        ..., description='Plazo de retención en archivo central o histórico (en años)'
    )
    plazo_gestion: conint(ge=0, le=65535) = Field(
        ..., description='Plazo de retención en archivo de gestión (en años)'
    )
    serie_documental: str = Field(
        ..., description='Serie o subserie documental a la que aplica'
    )


class UserRole(Enum):
    administrador = 'administrador'
    productor = 'productor'
    usuario_final = 'usuario_final'
    auditor = 'auditor'


class RelationType(Model):
    pass


class AuditRecord(BaseModel):
    accion: AuditAction = Field(
        ..., description='Tipo de acción realizada (crear, modificar, eliminar, etc.)'
    )
    descripcion: Optional[str] = Field(
        None, description='Descripción o detalle adicional del evento'
    )
    entidad_id: Optional[UUID] = Field(
        None, description='Identificador del documento o entidad afectada'
    )
    hash_actual: str = Field(
        ..., description='Hash actual calculado sobre el contenido de este registro'
    )
    hash_anterior: Optional[str] = Field(
        None, description='Hash del registro anterior (encadenamiento)'
    )
    id: UUID = Field(..., description='Identificador único del registro de auditoría')
    rol: UserRole = Field(..., description='Rol del usuario en el momento de la acción')
    timestamp: datetime = Field(
        ..., description='Fecha y hora exacta de la acción (UTC)'
    )
    usuario: str = Field(..., description='Usuario que ejecutó la acción')


class DocumentMetadata(BaseModel):
    descripcion: Optional[str] = Field(
        None, description='Descripción opcional del contenido'
    )
    estado: DocumentStatus = Field(
        ..., description='Estado del documento en su ciclo de vida'
    )
    fecha_creacion: datetime = Field(..., description='Fecha de creación o registro')
    formato: str = Field(..., description='Formato del archivo (PDF, DOCX, etc.)')
    id: UUID = Field(..., description='Identificador único e inalterable del documento')
    nivel_acceso: AccessLevel = Field(
        ..., description='Nivel de acceso (público, interno, confidencial)'
    )
    palabras_clave: Optional[list[str]] = Field(
        None, description='Palabras clave o etiquetas'
    )
    productor: str = Field(..., description='Productor o unidad responsable')
    relacionados: Optional[list[UUID]] = Field(
        None, description='Relación con otros documentos (anexos, versiones, etc.)'
    )
    tipo: DocumentType = Field(..., description='Tipo documental o género')
    titulo: str = Field(..., description='Título o asunto del documento')


class DocumentRelation(BaseModel):
    descripcion: Optional[str] = Field(
        None, description='Descripción opcional o nota sobre la relación'
    )
    documento_id: UUID = Field(..., description='ID del documento principal')
    documento_relacionado_id: UUID = Field(
        ..., description='ID del documento relacionado'
    )
    id: UUID = Field(..., description='Identificador único de la relación')
    tipo: Any = Field(..., description='Tipo de relación (anexo, versión, etc.)')


class UserInfo(BaseModel):
    activo: bool = Field(
        ..., description='Estado de la cuenta (activo, suspendido, etc.)'
    )
    correo: str = Field(..., description='Correo electrónico institucional')
    id: UUID = Field(..., description='Identificador único del usuario')
    nombre: str = Field(..., description='Nombre completo o alias')
    rol: UserRole = Field(..., description='Rol del usuario dentro del sistema')
    ultimo_acceso: Optional[datetime] = Field(
        None, description='Fecha de último acceso al sistema'
    )
